ALTER TABLE nodes
    ADD COLUMN IF NOT EXISTS cpu_model    TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cpu_cores    INT  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cpu_sockets  INT  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cpu_threads  INT  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cpu_mhz      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS kernel_version TEXT NOT NULL DEFAULT '';
