package api

import (
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"testing"

	"github.com/gofiber/fiber/v3"

	"github.com/bigjakk/nexara/internal/api/apischema"
)

// A migrated handler reads its validated request as p.String("size"), and reading a key
// the endpoint's own Parameters schema does not declare PANICS by design (apischema treats
// it as a programming error). This guard turns that panic into a build-time failure by
// walking each handler's source, and every same-package function it threads its
// *apischema.Params into, transitively, for accessor calls whose key is a string literal.
// resolveHandlerDecl finds a handler by package directory plus funcKey, not by
// runtime.Func.FileLine, which reports "<autogenerated>:1" for the BOUND METHOD VALUE
// (h.AttachDisk) every real handler is: a first version resolved zero real handlers, and
// its own package-level-function probes never noticed. The probes below are bound
// method values for that reason.

// paramAccessors are the *apischema.Params methods whose first argument names a declared
// parameter (Raw takes no key; mustProp and declared are unreachable from a handler);
// TestParamAccessorsCoversEveryStringKeyedMethod keeps it honest against the method set.
var paramAccessors = map[string]bool{
	"String": true, "Int": true, "Float": true, "Bool": true, "Strings": true, "Object": true,
	"OptString": true, "OptInt": true, "OptFloat": true, "OptBool": true, "Has": true,
}

// paramKeyGuardAnchor lets apiPackageImportPath find this package's import path by
// reflection instead of a module-path literal a rename would desync.
func paramKeyGuardAnchor() {}

// apiPackageImportPath is this package's own import path.
var apiPackageImportPath = func() string {
	full := runtime.FuncForPC(reflect.ValueOf(paramKeyGuardAnchor).Pointer()).Name()
	if i := strings.LastIndex(full, "."); i >= 0 {
		return full[:i]
	}
	return full
}()

// relPackageDir maps an import path to its source directory relative to the test's working
// directory (the package's own). Only internal/api and its subpackages resolve; anything
// else fails closed.
func relPackageDir(importPath string) (string, bool) {
	if importPath == apiPackageImportPath {
		return ".", true
	}
	prefix := apiPackageImportPath + "/"
	if !strings.HasPrefix(importPath, prefix) {
		return "", false
	}
	return importPath[len(prefix):], true
}

// splitRuntimeName splits a runtime.Func.Name() (any "-fm" suffix already trimmed) into the
// declaring package's import path and the funcKey-shaped name ("Type.Method" or a bare
// name) a *ast.FuncDecl would report: the general form of routeHandlerKey's extraction,
// freed from its "/handlers." assumption since this guard's probes are declared in package api.
func splitRuntimeName(full string) (importPath, key string) {
	prefix, tail := "", full
	if i := strings.LastIndex(full, "/"); i >= 0 {
		prefix, tail = full[:i+1], full[i+1:]
	}
	dot := strings.Index(tail, ".")
	if dot == -1 {
		return "", ""
	}
	importPath = prefix + tail[:dot]
	key = tail[dot+1:]
	key = strings.ReplaceAll(key, "(*", "")
	key = strings.ReplaceAll(key, ")", "")
	return importPath, key
}

// packageFuncDecls parses every .go file directly inside dir, test files included (a
// handler's callees and this guard's probes can live in either), and indexes each top-level
// function and method by funcKey; no recursion into subdirectories. It is parsed once per
// directory and shared, since the guard resolves ~535 handlers to their package (parsing the
// handlers directory for each was ~600 s of the race suite). Callers only read the map.
func packageFuncDecls(dir string) (map[string]*ast.FuncDecl, error) {
	v, _ := packageFuncDeclsCache.LoadOrStore(dir, &packageFuncDeclsEntry{})
	e := v.(*packageFuncDeclsEntry)
	e.once.Do(func() { e.decls, e.err = parsePackageFuncDecls(dir) })
	return e.decls, e.err
}

type packageFuncDeclsEntry struct {
	once  sync.Once
	decls map[string]*ast.FuncDecl
	err   error
}

var packageFuncDeclsCache sync.Map // dir → *packageFuncDeclsEntry

func parsePackageFuncDecls(dir string) (map[string]*ast.FuncDecl, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}
	out := map[string]*ast.FuncDecl{}
	for _, path := range paths {
		astFile, parseErr := parsedSource(path)
		if parseErr != nil {
			return nil, fmt.Errorf("parse %s: %w", path, parseErr)
		}
		for _, decl := range astFile.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Body == nil {
				continue
			}
			out[funcKey(fd)] = fd
		}
	}
	return out, nil
}

// parsedSource is path parsed once per test binary, positions in parsedSourceFset: the
// guards that read this package's source or handlers/ share one parse of each file
// instead of parsing it again. Callers only read the tree.
func parsedSource(path string) (*ast.File, error) {
	v, _ := parsedSourceCache.LoadOrStore(path, &parsedSourceEntry{})
	e := v.(*parsedSourceEntry)
	e.once.Do(func() { e.file, e.err = parser.ParseFile(parsedSourceFset, path, nil, parser.SkipObjectResolution) })
	return e.file, e.err
}

type parsedSourceEntry struct {
	once sync.Once
	file *ast.File
	err  error
}

var (
	parsedSourceFset  = token.NewFileSet()
	parsedSourceCache sync.Map // path → *parsedSourceEntry
)

// flatParam is one position in a function's flattened parameter list —
// see flattenParams.
type flatParam struct {
	name string
	typ  ast.Expr
}

// flattenParams expands fd's parameter list into one entry per argument
// POSITION, so it lines up 1:1 with a call expression's Args — a single
// *ast.Field can group several names under one type (func f(a, b string)).
func flattenParams(fd *ast.FuncDecl) []flatParam {
	if fd.Type.Params == nil {
		return nil
	}
	var out []flatParam
	for _, field := range fd.Type.Params.List {
		if len(field.Names) == 0 {
			out = append(out, flatParam{typ: field.Type})
			continue
		}
		for _, n := range field.Names {
			out = append(out, flatParam{name: n.Name, typ: field.Type})
		}
	}
	return out
}

// isParamsPointerType reports whether t is *apischema.Params.
func isParamsPointerType(t ast.Expr) bool {
	star, ok := t.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Params" {
		return false
	}
	pkgIdent, ok := sel.X.(*ast.Ident)
	return ok && pkgIdent.Name == "apischema"
}

// paramsArgName returns the name of fd's *apischema.Params parameter,
// resolved from the signature rather than assumed to be spelled "p" or
// "params" everywhere, so the accessor walk below only matches calls on
// the identifier the function itself binds.
func paramsArgName(fd *ast.FuncDecl) (string, bool) {
	for _, p := range flattenParams(fd) {
		if p.name != "" && isParamsPointerType(p.typ) {
			return p.name, true
		}
	}
	return "", false
}

// findThreadedParamsArg reports whether call passes the identifier
// paramName as an argument landing in calleeDecl's OWN
// *apischema.Params parameter — and if so, that parameter's name inside
// calleeDecl, which is what the transitive walk should look for in its
// body. Position-matched against call.Args, which (for a method call)
// excludes the receiver, matching flattenParams' ordering.
func findThreadedParamsArg(call *ast.CallExpr, paramName string, calleeDecl *ast.FuncDecl) (string, bool) {
	flat := flattenParams(calleeDecl)
	for i, arg := range call.Args {
		id, ok := arg.(*ast.Ident)
		if !ok || id.Name != paramName || i >= len(flat) {
			continue
		}
		if isParamsPointerType(flat[i].typ) && flat[i].name != "" {
			return flat[i].name, true
		}
	}
	return "", false
}

// resolveHandlerDecl locates h's own *ast.FuncDecl, its receiver type, every top-level
// declaration of its package (for the transitive walk) and the name its *apischema.Params
// argument is bound to, via reflect and runtime (see the top comment for why not FileLine).
func resolveHandlerDecl(h Handler) (fd *ast.FuncDecl, recvType string, decls map[string]*ast.FuncDecl, paramName string, err error) {
	pc := reflect.ValueOf(h).Pointer()
	rf := runtime.FuncForPC(pc)
	if rf == nil {
		return nil, "", nil, "", errors.New("could not resolve handler to a compiled function")
	}
	full := strings.TrimSuffix(rf.Name(), "-fm")
	importPath, wantKey := splitRuntimeName(full)
	if wantKey == "" {
		return nil, "", nil, "", fmt.Errorf("could not parse a declaration name out of %q", rf.Name())
	}
	dir, ok := relPackageDir(importPath)
	if !ok {
		return nil, "", nil, "", fmt.Errorf("%s is declared in %s, which is not internal/api or a "+
			"subpackage of it — this guard only resolves handlers there", wantKey, importPath)
	}
	decls, err = packageFuncDecls(dir)
	if err != nil {
		return nil, "", nil, "", err
	}
	fd, ok = decls[wantKey]
	if !ok {
		return nil, "", nil, "", fmt.Errorf("%s: no top-level function declaration named %s "+
			"(a closure has no declaration of its own to walk)", dir, wantKey)
	}
	paramName, ok = paramsArgName(fd)
	if !ok {
		return nil, "", nil, "", fmt.Errorf("%s does not take an *apischema.Params argument", wantKey)
	}
	return fd, receiverType(fd), decls, paramName, nil
}

// checkAccessorCall reports the violation for one Params accessor call, or ("", false) when
// it is clean or cannot be verified statically (a non-literal key, the limitation
// rbac_route_guard_test.go's call-graph walk shares for a dynamic permission action).
func checkAccessorCall(methodName string, call *ast.CallExpr, schema apischema.Properties) (string, bool) {
	if len(call.Args) == 0 {
		return "", false
	}
	lit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	key, unquoteErr := strconv.Unquote(lit.Value)
	if unquoteErr != nil {
		return "", false
	}
	if _, declared := schema[key]; declared {
		return "", false
	}
	return fmt.Sprintf(
		"handler calls params.%s(%q), but %q is not declared in this endpoint's Parameters — "+
			"reading it panics at request time (apischema: Params accessors panic on an undeclared key)",
		methodName, key, key), true
}

// walkForUndeclaredParamKeys walks fd's body for Params accessor calls on paramName and
// recurses into a same-package callee that receives paramName, so a handler delegating to a
// helper is checked like one that reads the key directly (calleeKey's same-package-only
// limitation is shared with rbac_route_guard_test.go). seen stops call cycles and double
// reports on a diamond; keying by funcKey alone is safe because paramsArgName never
// depends on how a declaration was reached.
func walkForUndeclaredParamKeys(fd *ast.FuncDecl, paramName, recvType string, decls map[string]*ast.FuncDecl, seen map[string]bool, schema apischema.Properties) []string {
	key := funcKey(fd)
	if seen[key] {
		return nil
	}
	seen[key] = true

	var out []string
	ast.Inspect(fd.Body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}

		if sel, isSel := call.Fun.(*ast.SelectorExpr); isSel && paramAccessors[sel.Sel.Name] {
			if recv, ok := sel.X.(*ast.Ident); ok && recv.Name == paramName {
				if msg, bad := checkAccessorCall(sel.Sel.Name, call, schema); bad {
					out = append(out, msg)
				}
				return true
			}
		}

		callee := calleeKey(call.Fun, recvType)
		if callee == "" {
			return true
		}
		calleeDecl, ok := decls[callee]
		if !ok {
			return true
		}
		calleeParamName, threaded := findThreadedParamsArg(call, paramName, calleeDecl)
		if !threaded {
			return true
		}
		out = append(out, walkForUndeclaredParamKeys(calleeDecl, calleeParamName, receiverType(calleeDecl), decls, seen, schema)...)
		return true
	})
	return out
}

// registryUndeclaredParamKeys reports, for every endpoint in eps, every string-literal key a
// Params accessor call names, in its handler or in a same-package function the handler
// threads its Params into, that the endpoint's Parameters schema does not declare.
func registryUndeclaredParamKeys(eps []Endpoint) []string {
	var out []string
	for _, e := range eps {
		fd, recvType, decls, paramName, err := resolveHandlerDecl(e.Handler)
		if err != nil {
			out = append(out, fmt.Sprintf("%s %s: %v", e.Method, e.Path, err))
			continue
		}
		seen := map[string]bool{}
		for _, msg := range walkForUndeclaredParamKeys(fd, paramName, recvType, decls, seen, e.Parameters) {
			out = append(out, fmt.Sprintf("%s %s: %s", e.Method, e.Path, msg))
		}
	}
	return out
}

// TestGuard_RegistryHandlersOnlyReadDeclaredParams is the production guard. Its registry
// comes from a real Server: a handler is a bound method value, so no declarations exist
// until a Server builds them, and a global would have passed on an empty slice.
func TestGuard_RegistryHandlersOnlyReadDeclaredParams(t *testing.T) {
	s := sharedRouteStub(t)
	if s.registry.Len() == 0 {
		t.Fatal("the server registered no endpoints, so this guard would check nothing")
	}
	for _, msg := range registryUndeclaredParamKeys(s.registry.Endpoints()) {
		t.Error(msg)
	}
}

// TestParamAccessorsCoversEveryStringKeyedMethod keeps paramAccessors honest against
// apischema.Params' method set: a new accessor with a leading string key missing from it
// would silently escape the walk.
func TestParamAccessorsCoversEveryStringKeyedMethod(t *testing.T) {
	typ := reflect.TypeOf(&apischema.Params{})
	for i := 0; i < typ.NumMethod(); i++ {
		m := typ.Method(i)
		if m.Func.Type().NumIn() < 2 {
			continue // no argument beyond the receiver (e.g. Raw)
		}
		if m.Func.Type().In(1).Kind() != reflect.String {
			continue // first argument is not a string key
		}
		if !paramAccessors[m.Name] {
			t.Errorf("apischema.Params.%s takes a leading string argument but is not in paramAccessors — "+
				"registryUndeclaredParamKeys will not check calls to it", m.Name)
		}
	}
}

// paramKeyGuardProbe is a type in this file used as a BOUND METHOD VALUE, the shape every
// real handler has (see the top comment); the receiver is "h" so calleeKey recognises it.
type paramKeyGuardProbe struct{}

func (h paramKeyGuardProbe) undeclaredKey(_ fiber.Ctx, p *apischema.Params) error {
	_ = p.String("undeclared_probe_key")
	return nil
}

func (h paramKeyGuardProbe) declaredKeys(_ fiber.Ctx, p *apischema.Params) error {
	_ = p.String("size")
	_, _ = p.OptInt("index")
	_ = p.Has("format")
	return nil
}

func (h paramKeyGuardProbe) dynamicKey(_ fiber.Ctx, p *apischema.Params) error {
	key := "size"
	_ = p.String(key)
	return nil
}

func (h paramKeyGuardProbe) callsHelperWithUndeclaredKey(c fiber.Ctx, p *apischema.Params) error {
	return h.helperReadsUndeclaredKey(c, p)
}

func (h paramKeyGuardProbe) helperReadsUndeclaredKey(_ fiber.Ctx, p *apischema.Params) error {
	_ = p.String("undeclared_via_helper")
	return nil
}

// TestRegistryUndeclaredParamKeys_CatchesAnUndeclaredKey drives registryUndeclaredParamKeys
// over probes, since the real registry is clean: an undeclared key in a bound method value;
// one read in a helper the handler calls (the transitive walk); a closure, which has no
// declaration to walk and must be reported, with the wording that tells it from the
// "<autogenerated>" resolution bug (a real handler once produced "parse <autogenerated>"
// and still satisfied a bare length check); and the reads that must not be flagged,
// declared keys across String/OptInt/Has and a non-literal key.
func TestRegistryUndeclaredParamKeys_CatchesAnUndeclaredKey(t *testing.T) {
	probe := paramKeyGuardProbe{}
	declared := apischema.Properties{
		"size":   {Type: apischema.String},
		"index":  {Type: apischema.Integer, Optional: true},
		"format": {Type: apischema.String, Optional: true},
	}
	for _, tt := range []struct {
		name    string
		handler Handler
		params  apischema.Properties
		want    string // the one violation must carry it; empty: none
	}{
		{"an undeclared key", probe.undeclaredKey, nil, "undeclared_probe_key"},
		{"an undeclared key in a helper", probe.callsHelperWithUndeclaredKey, nil, "undeclared_via_helper"},
		{"a closure", func(_ fiber.Ctx, _ *apischema.Params) error { return nil }, nil, "no top-level function declaration named"},
		{"declared keys", probe.declaredKeys, declared, ""},
		{"a non-literal key", probe.dynamicKey, nil, ""},
	} {
		t.Run(tt.name, func(t *testing.T) {
			reg := NewRegistry()
			reg.Register(registryProbeEndpoint("/api/v1/probe", Permissions{Public: "synthetic route for the param-key guard test"},
				tt.handler, tt.params))
			got := registryUndeclaredParamKeys(reg.Endpoints())
			if tt.want == "" {
				if len(got) != 0 {
					t.Fatalf("violations = %v, want none", got)
				}
				return
			}
			if len(got) != 1 || !strings.Contains(got[0], tt.want) {
				t.Fatalf("violations = %v, want exactly 1 carrying %q", got, tt.want)
			}
		})
	}
}
