package api

import (
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"

	"github.com/gofiber/fiber/v3"

	"github.com/bigjakk/nexara/internal/api/apischema"
)

// A migrated handler reads its validated request as p.String("size"),
// p.OptInt("index"), p.Has("format") and so on — apischema.Params' whole
// design (see its package comment). Reading a key the endpoint's own
// Parameters schema does not declare PANICS by design: apischema treats
// that as a programming error, not a request the caller could get wrong,
// because the schema sits a few lines above the accessor call and nothing
// about a bad key can be blamed on the request. This guard turns that
// panic into a build-time failure instead, by walking the handler's own
// source — and every same-package function it calls that also receives
// the *apischema.Params value, transitively — for every Params-accessor
// call whose key is a string literal, checked against the schema.
//
// It currently matches zero handlers, because nothing is migrated yet —
// see TestGuard_RegistryHandlersOnlyReadDeclaredParams below. That alone
// would make it a vacuous guard (a check whose input cannot express
// failure — a bug class this repo has hit before; see
// rbac_route_guard_test.go's own LIMITATION note for the shape of it), so
// the tests further down drive registryUndeclaredParamKeys over synthetic
// endpoints and assert it reports what it should — and, just as
// importantly, does NOT report what it should not.
//
// A first version of this guard resolved a handler's source file via
// runtime.Func.FileLine, which reports "<autogenerated>:1" for a BOUND
// METHOD VALUE — h.AttachDisk, the shape every real handler in this
// codebase actually is (see internal/api/CLAUDE.md and routeHandlerKey's
// own doc comment, which names handlers.(*VMHandler).PerformAction-fm as
// its running example). FileLine is only reliable for a plain
// package-level function, which is the one shape no real handler is — so
// that version resolved zero real handlers, ever, and its own tests never
// caught it because every probe they used WAS a package-level function.
// resolveHandlerDecl below resolves by package directory + funcKey match
// instead (the same technique buildCallGraph already uses to glob
// handlers/*.go), which works for both shapes, and
// TestRegistryUndeclaredParamKeys_CatchesAnUndeclaredKey now drives a
// bound method value specifically so this cannot regress unnoticed again.

// paramAccessors are the *apischema.Params methods whose first argument
// names a declared parameter. Raw and the unexported mustProp/declared
// are absent on purpose: Raw takes no key, and the other two are not
// reachable from a handler. TestParamAccessorsCoversEveryStringKeyedMethod
// keeps this list honest against apischema.Params' actual method set.
var paramAccessors = map[string]bool{
	"String": true, "Int": true, "Float": true, "Bool": true, "Strings": true,
	"OptString": true, "OptInt": true, "OptFloat": true, "OptBool": true, "Has": true,
}

// paramKeyGuardAnchor exists only so apiPackageImportPath can discover
// this package's own import path via reflection, rather than hardcoding
// the module path as a string literal that a rename would silently
// desync.
func paramKeyGuardAnchor() {}

// apiPackageImportPath is this package's own import path.
var apiPackageImportPath = func() string {
	full := runtime.FuncForPC(reflect.ValueOf(paramKeyGuardAnchor).Pointer()).Name()
	if i := strings.LastIndex(full, "."); i >= 0 {
		return full[:i]
	}
	return full
}()

// relPackageDir maps a fully-qualified import path to the filesystem
// directory holding its source, relative to this test binary's working
// directory — which `go test` sets to the PACKAGE's own source directory,
// the same assumption buildCallGraph's "handlers" glob already relies on.
// Only internal/api itself and its subpackages resolve; anything else
// fails closed rather than guessing at a directory that might not even be
// checked out relative to here.
func relPackageDir(importPath string) (string, bool) {
	if importPath == apiPackageImportPath {
		return ".", true
	}
	prefix := apiPackageImportPath + "/"
	if !strings.HasPrefix(importPath, prefix) {
		return "", false
	}
	return importPath[len(prefix):], true
}

// splitRuntimeName splits a runtime.Func.Name() result (with any "-fm"
// bound-method-value suffix already trimmed by the caller) into the
// declaring package's import path and the funcKey-shaped name
// ("Type.Method" or a bare name) a *ast.FuncDecl for the same declaration
// would report — e.g.
// "github.com/bigjakk/nexara/internal/api/handlers.(*VMHandler).PerformAction"
// becomes ("github.com/bigjakk/nexara/internal/api/handlers", "VMHandler.PerformAction").
// It is the general form of the extraction routeHandlerKey does, freed
// from that function's "/handlers." assumption: this guard's own
// synthetic probes are declared in package api, not handlers.
func splitRuntimeName(full string) (importPath, key string) {
	prefix, tail := "", full
	if i := strings.LastIndex(full, "/"); i >= 0 {
		prefix, tail = full[:i+1], full[i+1:]
	}
	dot := strings.Index(tail, ".")
	if dot == -1 {
		return "", ""
	}
	importPath = prefix + tail[:dot]
	key = tail[dot+1:]
	key = strings.ReplaceAll(key, "(*", "")
	key = strings.ReplaceAll(key, ")", "")
	return importPath, key
}

// packageFuncDecls parses every .go file directly inside dir — both
// regular and _test.go files, since a handler's transitive callees and
// this guard's own synthetic probes can each legitimately live in either
// — and indexes every top-level function/method declaration by its
// funcKey. It does not recurse into subdirectories. Go itself refuses two
// declarations with the same funcKey in one package, so the index cannot
// collide.
func packageFuncDecls(dir string) (map[string]*ast.FuncDecl, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}
	fset := token.NewFileSet()
	out := map[string]*ast.FuncDecl{}
	for _, path := range paths {
		astFile, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			return nil, fmt.Errorf("parse %s: %w", path, parseErr)
		}
		for _, decl := range astFile.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Body == nil {
				continue
			}
			out[funcKey(fd)] = fd
		}
	}
	return out, nil
}

// flatParam is one position in a function's flattened parameter list —
// see flattenParams.
type flatParam struct {
	name string
	typ  ast.Expr
}

// flattenParams expands fd's parameter list into one entry per argument
// POSITION, so it lines up 1:1 with a call expression's Args — a single
// *ast.Field can group several names under one type (func f(a, b string)).
func flattenParams(fd *ast.FuncDecl) []flatParam {
	if fd.Type.Params == nil {
		return nil
	}
	var out []flatParam
	for _, field := range fd.Type.Params.List {
		if len(field.Names) == 0 {
			out = append(out, flatParam{typ: field.Type})
			continue
		}
		for _, n := range field.Names {
			out = append(out, flatParam{name: n.Name, typ: field.Type})
		}
	}
	return out
}

// isParamsPointerType reports whether t is *apischema.Params.
func isParamsPointerType(t ast.Expr) bool {
	star, ok := t.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Params" {
		return false
	}
	pkgIdent, ok := sel.X.(*ast.Ident)
	return ok && pkgIdent.Name == "apischema"
}

// paramsArgName returns the name of fd's *apischema.Params parameter,
// resolved from the signature rather than assumed to be spelled "p" or
// "params" everywhere, so the accessor walk below only matches calls on
// the identifier the function itself binds.
func paramsArgName(fd *ast.FuncDecl) (string, bool) {
	for _, p := range flattenParams(fd) {
		if p.name != "" && isParamsPointerType(p.typ) {
			return p.name, true
		}
	}
	return "", false
}

// findThreadedParamsArg reports whether call passes the identifier
// paramName as an argument landing in calleeDecl's OWN
// *apischema.Params parameter — and if so, that parameter's name inside
// calleeDecl, which is what the transitive walk should look for in its
// body. Position-matched against call.Args, which (for a method call)
// excludes the receiver, matching flattenParams' ordering.
func findThreadedParamsArg(call *ast.CallExpr, paramName string, calleeDecl *ast.FuncDecl) (string, bool) {
	flat := flattenParams(calleeDecl)
	for i, arg := range call.Args {
		id, ok := arg.(*ast.Ident)
		if !ok || id.Name != paramName || i >= len(flat) {
			continue
		}
		if isParamsPointerType(flat[i].typ) && flat[i].name != "" {
			return flat[i].name, true
		}
	}
	return "", false
}

// resolveHandlerDecl locates h's own *ast.FuncDecl, its receiver type (for
// resolving further same-package calls from its body via calleeKey in
// rbac_route_guard_test.go), every top-level declaration in the same
// directory (for the transitive walk to resolve a callee against without
// re-parsing per call), and the name h's *apischema.Params argument is
// bound to.
//
// It resolves h's compiled address to a declaring package and a funcKey
// via reflect + runtime — the same runtime.Func.Name() routeHandlerKey
// reads — then parses that package's directory looking for a matching
// declaration. See the file's top comment for why FileLine cannot do this
// job.
func resolveHandlerDecl(h Handler) (fd *ast.FuncDecl, recvType string, decls map[string]*ast.FuncDecl, paramName string, err error) {
	pc := reflect.ValueOf(h).Pointer()
	rf := runtime.FuncForPC(pc)
	if rf == nil {
		return nil, "", nil, "", errors.New("could not resolve handler to a compiled function")
	}
	full := strings.TrimSuffix(rf.Name(), "-fm")
	importPath, wantKey := splitRuntimeName(full)
	if wantKey == "" {
		return nil, "", nil, "", fmt.Errorf("could not parse a declaration name out of %q", rf.Name())
	}
	dir, ok := relPackageDir(importPath)
	if !ok {
		return nil, "", nil, "", fmt.Errorf("%s is declared in %s, which is not internal/api or a "+
			"subpackage of it — this guard only resolves handlers there", wantKey, importPath)
	}
	decls, err = packageFuncDecls(dir)
	if err != nil {
		return nil, "", nil, "", err
	}
	fd, ok = decls[wantKey]
	if !ok {
		return nil, "", nil, "", fmt.Errorf("%s: no top-level function declaration named %s "+
			"(a closure has no declaration of its own to walk)", dir, wantKey)
	}
	paramName, ok = paramsArgName(fd)
	if !ok {
		return nil, "", nil, "", fmt.Errorf("%s does not take an *apischema.Params argument", wantKey)
	}
	return fd, receiverType(fd), decls, paramName, nil
}

// checkAccessorCall reports the violation message for a single Params
// accessor call, or ("", false) if the call is clean or cannot be
// verified statically (a non-literal key — the same documented limitation
// rbac_route_guard_test.go's own call-graph walk carries for a fully
// dynamic permission action).
func checkAccessorCall(methodName string, call *ast.CallExpr, schema apischema.Properties) (string, bool) {
	if len(call.Args) == 0 {
		return "", false
	}
	lit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	key, unquoteErr := strconv.Unquote(lit.Value)
	if unquoteErr != nil {
		return "", false
	}
	if _, declared := schema[key]; declared {
		return "", false
	}
	return fmt.Sprintf(
		"handler calls params.%s(%q), but %q is not declared in this endpoint's Parameters — "+
			"reading it panics at request time (apischema: Params accessors panic on an undeclared key)",
		methodName, key, key), true
}

// walkForUndeclaredParamKeys walks fd's body for Params accessor calls on
// paramName, and — for a call to another same-package function or method
// that also receives paramName into ITS OWN *apischema.Params parameter —
// recurses into that function too, so a handler that delegates to a
// helper (return h.build(c, p)) is checked the same as one that reads the
// key directly. This mirrors the transitive reach
// callGraph.reachesPermissionCheck proves for a permission check.
//
// recvType is fd's own receiver type (receiverType(fd)), needed to
// resolve calleeKey's receiver-qualified calls; calleeKey and its
// "same-package only" limitation are reused from
// rbac_route_guard_test.go rather than reimplemented — a call into
// another package cannot be resolved this way and is silently not
// followed.
//
// seen prevents infinite recursion on a call cycle and duplicate
// reporting on a diamond (two callers reaching the same helper); keyed by
// funcKey alone, which is safe because a declaration's own paramsArgName
// result never depends on how it was reached.
func walkForUndeclaredParamKeys(fd *ast.FuncDecl, paramName, recvType string, decls map[string]*ast.FuncDecl, seen map[string]bool, schema apischema.Properties) []string {
	key := funcKey(fd)
	if seen[key] {
		return nil
	}
	seen[key] = true

	var out []string
	ast.Inspect(fd.Body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}

		if sel, isSel := call.Fun.(*ast.SelectorExpr); isSel && paramAccessors[sel.Sel.Name] {
			if recv, ok := sel.X.(*ast.Ident); ok && recv.Name == paramName {
				if msg, bad := checkAccessorCall(sel.Sel.Name, call, schema); bad {
					out = append(out, msg)
				}
				return true
			}
		}

		callee := calleeKey(call.Fun, recvType)
		if callee == "" {
			return true
		}
		calleeDecl, ok := decls[callee]
		if !ok {
			return true
		}
		calleeParamName, threaded := findThreadedParamsArg(call, paramName, calleeDecl)
		if !threaded {
			return true
		}
		out = append(out, walkForUndeclaredParamKeys(calleeDecl, calleeParamName, receiverType(calleeDecl), decls, seen, schema)...)
		return true
	})
	return out
}

// registryUndeclaredParamKeys reports, for every endpoint in eps, every
// string-literal key a Params accessor call — inside its handler, or
// inside any same-package function the handler threads its Params value
// into, transitively — names that the endpoint's own Parameters schema
// does not declare.
func registryUndeclaredParamKeys(eps []Endpoint) []string {
	var out []string
	for _, e := range eps {
		fd, recvType, decls, paramName, err := resolveHandlerDecl(e.Handler)
		if err != nil {
			out = append(out, fmt.Sprintf("%s %s: %v", e.Method, e.Path, err))
			continue
		}
		seen := map[string]bool{}
		for _, msg := range walkForUndeclaredParamKeys(fd, paramName, recvType, decls, seen, e.Parameters) {
			out = append(out, fmt.Sprintf("%s %s: %s", e.Method, e.Path, msg))
		}
	}
	return out
}

// TestGuard_RegistryHandlersOnlyReadDeclaredParams is the production
// guard. It iterates zero times today — see the file's top comment — and
// starts doing real work the moment Phase 4 registers its first endpoint.
func TestGuard_RegistryHandlersOnlyReadDeclaredParams(t *testing.T) {
	for _, msg := range registryUndeclaredParamKeys(endpoints.Endpoints()) {
		t.Error(msg)
	}
}

// TestParamAccessorsCoversEveryStringKeyedMethod keeps paramAccessors
// honest against apischema.Params' actual method set: a future accessor
// (an OptStrings, say) that takes a leading string key but is never added
// to paramAccessors would silently escape registryUndeclaredParamKeys'
// walk — this makes that a build failure instead of a quiet gap.
func TestParamAccessorsCoversEveryStringKeyedMethod(t *testing.T) {
	typ := reflect.TypeOf(&apischema.Params{})
	for i := 0; i < typ.NumMethod(); i++ {
		m := typ.Method(i)
		if m.Func.Type().NumIn() < 2 {
			continue // no argument beyond the receiver (e.g. Raw)
		}
		if m.Func.Type().In(1).Kind() != reflect.String {
			continue // first argument is not a string key
		}
		if !paramAccessors[m.Name] {
			t.Errorf("apischema.Params.%s takes a leading string argument but is not in paramAccessors — "+
				"registryUndeclaredParamKeys will not check calls to it", m.Name)
		}
	}
}

// paramKeyGuardProbe is a small type living directly in this test file,
// used as a BOUND METHOD VALUE — h.undeclaredKey, not a package-level
// function — the way every real handler in this codebase actually is.
// See the file's top comment for why that distinction is the whole point:
// a package-level probe alone would not have caught resolveHandlerDecl's
// original bug. The receiver is named "h" specifically so calleeKey
// (rbac_route_guard_test.go) recognizes it as a receiver, matching the
// codebase-wide handler convention isReceiverName documents.
type paramKeyGuardProbe struct{}

func (h paramKeyGuardProbe) undeclaredKey(_ fiber.Ctx, p *apischema.Params) error {
	_ = p.String("undeclared_probe_key")
	return nil
}

func (h paramKeyGuardProbe) declaredKeys(_ fiber.Ctx, p *apischema.Params) error {
	_ = p.String("size")
	_, _ = p.OptInt("index")
	_ = p.Has("format")
	return nil
}

func (h paramKeyGuardProbe) dynamicKey(_ fiber.Ctx, p *apischema.Params) error {
	key := "size"
	_ = p.String(key)
	return nil
}

// callsHelperWithUndeclaredKey and helperReadsUndeclaredKey exist for
// TestRegistryUndeclaredParamKeys_TransitiveWalkCatchesAHelper: the
// undeclared key is read in a DIFFERENT function than the one Endpoint.Handler
// names.
func (h paramKeyGuardProbe) callsHelperWithUndeclaredKey(c fiber.Ctx, p *apischema.Params) error {
	return h.helperReadsUndeclaredKey(c, p)
}

func (h paramKeyGuardProbe) helperReadsUndeclaredKey(_ fiber.Ctx, p *apischema.Params) error {
	_ = p.String("undeclared_via_helper")
	return nil
}

// TestRegistryUndeclaredParamKeys_CatchesAnUndeclaredKey is the "prove it
// bites" test, driven over a BOUND METHOD VALUE — see paramKeyGuardProbe's
// doc comment for why that shape specifically is load-bearing here.
func TestRegistryUndeclaredParamKeys_CatchesAnUndeclaredKey(t *testing.T) {
	probe := paramKeyGuardProbe{}
	reg := NewRegistry()
	reg.Register(registryProbeEndpointNoParams("/api/v1/probe",
		Permissions{Public: "synthetic route for the param-key guard test"},
		probe.undeclaredKey))

	got := registryUndeclaredParamKeys(reg.Endpoints())
	if len(got) != 1 {
		t.Fatalf("violations = %v, want exactly 1", got)
	}
	if !strings.Contains(got[0], "undeclared_probe_key") {
		t.Errorf("violation = %q, want it to name the undeclared key", got[0])
	}
}

// TestRegistryUndeclaredParamKeys_DeclaredKeysPass is the negative case:
// every key the handler reads IS declared, across String/OptInt/Has, and
// none of it should be flagged.
func TestRegistryUndeclaredParamKeys_DeclaredKeysPass(t *testing.T) {
	probe := paramKeyGuardProbe{}
	reg := NewRegistry()
	reg.Register(registryProbeEndpoint("/api/v1/probe",
		Permissions{Public: "synthetic route for the param-key guard test"},
		probe.declaredKeys,
		apischema.Properties{
			"size":   {Type: apischema.String},
			"index":  {Type: apischema.Integer, Optional: true},
			"format": {Type: apischema.String, Optional: true},
		}))

	if got := registryUndeclaredParamKeys(reg.Endpoints()); len(got) != 0 {
		t.Errorf("violations = %v, want none — every key the handler reads is declared", got)
	}
}

// TestRegistryUndeclaredParamKeys_DynamicKeyIsNotFlagged proves a
// non-literal key is left alone rather than mistaken for a violation.
func TestRegistryUndeclaredParamKeys_DynamicKeyIsNotFlagged(t *testing.T) {
	probe := paramKeyGuardProbe{}
	reg := NewRegistry()
	reg.Register(registryProbeEndpointNoParams("/api/v1/probe",
		Permissions{Public: "synthetic route for the param-key guard test"},
		probe.dynamicKey))

	if got := registryUndeclaredParamKeys(reg.Endpoints()); len(got) != 0 {
		t.Errorf("violations = %v, want none — a non-literal key cannot be verified statically", got)
	}
}

// TestRegistryUndeclaredParamKeys_TransitiveWalkCatchesAHelper proves the
// transitive reach: an undeclared key read inside a function the handler
// CALLS — not inside the handler's own body — is still caught.
func TestRegistryUndeclaredParamKeys_TransitiveWalkCatchesAHelper(t *testing.T) {
	probe := paramKeyGuardProbe{}
	reg := NewRegistry()
	reg.Register(registryProbeEndpointNoParams("/api/v1/probe",
		Permissions{Public: "synthetic route for the param-key guard test"},
		probe.callsHelperWithUndeclaredKey))

	got := registryUndeclaredParamKeys(reg.Endpoints())
	if len(got) != 1 {
		t.Fatalf("violations = %v, want exactly 1", got)
	}
	if !strings.Contains(got[0], "undeclared_via_helper") {
		t.Errorf("violation = %q, want it to name the key read inside the helper", got[0])
	}
}

// TestRegistryUndeclaredParamKeys_UnresolvableHandlerIsFlagged covers the
// fail-closed side of resolveHandlerDecl: a func literal has no
// *ast.FuncDecl of its own (funcKey only ever names a top-level
// declaration), so it cannot be walked at all — and "cannot verify" must
// be reported, not silently passed. The specific wording assertion
// (rather than a bare length check) is deliberate: it is what would have
// told this failure apart from the FileLine/"<autogenerated>" bug — a
// REAL handler's bound method value used to produce a "parse
// <autogenerated>: ..." error and STILL satisfy "len(got) == 1", which is
// exactly how that bug shipped unnoticed the first time.
func TestRegistryUndeclaredParamKeys_UnresolvableHandlerIsFlagged(t *testing.T) {
	reg := NewRegistry()
	reg.Register(registryProbeEndpointNoParams("/api/v1/probe",
		Permissions{Public: "synthetic route for the param-key guard test"},
		func(_ fiber.Ctx, _ *apischema.Params) error { return nil }))

	got := registryUndeclaredParamKeys(reg.Endpoints())
	if len(got) != 1 {
		t.Fatalf("violations = %v, want exactly 1", got)
	}
	if !strings.Contains(got[0], "no top-level function declaration named") {
		t.Errorf("violation = %q, want it to say no top-level declaration was found (a closure) — "+
			"not the <autogenerated> file-resolution failure this guard used to have", got[0])
	}
}
