package api

import (
	"github.com/gofiber/fiber/v3"

	"github.com/bigjakk/nexara/internal/api/apischema"
	"github.com/bigjakk/nexara/internal/api/handlers"
)

// The shared declaration vocabulary this file uses — globalCheck — lives in
// registry_vms.go, where the first migrated domain defined it. userScope and
// userIDParam come from registry_users.go, whose path prefix the admin reset
// shares.

// totpScope is where a caller manages their OWN second factor.
const totpScope = pathPrefix + "auth/totp"

// totpCodePatternRE is the six-digit TOTP code, as the handler's own
// totpCodePattern spells it. It is restated here rather than exported from the
// handlers package because a regexp.Regexp and a schema Pattern are different
// types; totp_test.go drives the handler's copy and
// TestTOTPCodePatternMatchesTheHandler pins that the two agree on what a code
// looks like.
const totpCodePatternRE = `^[0-9]{6}$`

// totpRequiredCodeParam is the code on the two routes that REQUIRE one.
//
// The pattern does the whole job here: it refuses the empty string as well as a
// malformed one, which is exactly the pair of checks the handlers made
// (`== ""`, then the regex).
func totpRequiredCodeParam(description string) apischema.Property {
	return apischema.Property{
		Type:        apischema.String,
		Pattern:     totpCodePatternRE,
		Typetext:    "<6 digits>",
		Description: description,
	}
}

// totpOptionalCodeParam is the code on the two routes that accept EITHER a code
// or a recovery code, and it deliberately carries NO pattern.
//
// Those handlers test `if req.Code != "" && !totpCodePattern.MatchString(...)`,
// so an explicitly empty code has always been legal there — it is how a client
// spells "I am using the recovery code instead". A Pattern would refuse it,
// because apischema treats "" as a value the caller supplied rather than as an
// omission, and `{"code":"","recovery_code":"..."}` would start answering 400
// on a request that works today. The regex therefore stays in the handler,
// where it can be conditional; what the declaration adds is the length bound
// and the closed parameter set.
func totpOptionalCodeParam(description string) apischema.Property {
	return apischema.Property{
		Type:        apischema.String,
		Optional:    true,
		MaxLength:   apischema.Ptr(6),
		Typetext:    "<6 digits>",
		Description: description,
	}
}

// totpRecoveryCodeParam is a single-use recovery code.
//
// No pattern: the codes are generated by auth.TOTPService and their alphabet is
// that generator's business, not this route's. The bound is generous on
// purpose — a recovery code that stopped being accepted because its format
// changed would lock an operator out of the account this endpoint exists to
// rescue.
var totpRecoveryCodeParam = apischema.Property{
	Type:      apischema.String,
	Optional:  true,
	MaxLength: apischema.Ptr(128),
	Typetext:  "<recovery code>",
	Description: "One of the single-use recovery codes issued at enrollment. Consumed on success; the " +
		"remaining count is on the status route.",
}

// registerTOTPEndpoints declares all 7 of TOTPHandler's routes.
//
// The split is the domain's own shape and every one of the three kinds is here:
//
//	5  SelfService  the caller's own enrollment — setup, confirm, disable,
//	                status and recovery-code regeneration. Every one takes its
//	                subject from c.Locals("user_id") and NONE of them names a
//	                subject in its path or body, which is the property
//	                SelfService has to establish.
//	1  Public       verify-login, the second factor of an in-progress login: the
//	                caller holds a pending token, not a session.
//	1  Check        the admin reset, which acts on SOMEBODY ELSE's enrollment
//	                and is therefore the one route here that needs a grant.
//
// The five SelfService reasons and the Public one are carried across VERBATIM
// from selfServiceRoutes and publicRoutes in rbac_route_guard_test.go, which
// are the reviewed lists these declarations fold into —
// TestTOTPExemptionReasonsMatchTheReviewedLists pins that they stay identical
// rather than drifting into two justifications for one exemption.
//
// What stays in the handlers is everything the declaration cannot see: the
// per-user lockout, the per-token attempt budget, the peek-without-consuming
// reads, and the "code or recovery_code, at least one" rule, which is
// cross-field and which apischema's Requires cannot express.
func registerTOTPEndpoints(reg *Registry, h *handlers.TOTPHandler) {
	reg.Register(Endpoint{
		Method: fiber.MethodPost,
		Path:   totpScope + "/verify-login",
		Description: "Complete a two-step login with a TOTP code or a recovery code. The pending token " +
			"comes from the login response; it survives a typo but self-destructs after five attempts, " +
			"and a per-user cooldown catches an attacker cycling fresh tokens.",
		Group:       "Two-Factor Authentication",
		Permissions: Permissions{Public: "second factor of an in-progress login"},
		Parameters: apischema.Properties{
			"totp_pending_token": {
				Type:        apischema.String,
				MinLength:   apischema.Ptr(1),
				MaxLength:   apischema.Ptr(256),
				Typetext:    "<token>",
				Description: "The short-lived challenge token the login response returned.",
			},
			"code":          totpOptionalCodeParam("Current authenticator code. Send this OR recovery_code."),
			"recovery_code": totpRecoveryCodeParam,
		},
		Handler: h.VerifyLogin,
	})

	reg.Register(Endpoint{
		Method: fiber.MethodPost,
		Path:   totpScope + "/setup",
		Description: "Begin enrolling the caller's own second factor: returns the secret and its " +
			"otpauth:// URL. Nothing is stored on the account until the enrollment is confirmed.",
		Group:       "Two-Factor Authentication",
		Permissions: Permissions{SelfService: "enrolls the caller's own second factor"},
		Parameters:  apischema.Properties{},
		Handler:     h.BeginSetup,
	})
	reg.Register(Endpoint{
		Method: fiber.MethodPost,
		Path:   totpScope + "/setup/verify",
		Description: "Confirm the caller's own enrollment with a code from the authenticator, and " +
			"receive the recovery codes. They are shown once; only their hashes are kept.",
		Group:       "Two-Factor Authentication",
		Permissions: Permissions{SelfService: "confirms the caller's own enrollment"},
		Parameters: apischema.Properties{
			"code": totpRequiredCodeParam("Current code from the authenticator being enrolled."),
		},
		Handler: h.ConfirmSetup,
	})
	reg.Register(Endpoint{
		Method: fiber.MethodDelete,
		Path:   totpScope,
		Description: "Disable the caller's own second factor. Requires a current code or a recovery " +
			"code, so a stolen access token alone cannot remove it.",
		Group:       "Two-Factor Authentication",
		Permissions: Permissions{SelfService: "disables the caller's own second factor"},
		Parameters: apischema.Properties{
			// Source is stated EXPLICITLY on both, and that is the
			// load-bearing part of this declaration. ResolveSource reads an
			// unsourced parameter on DELETE out of the QUERY STRING, and the
			// SPA sends these in a JSON body — so leaving it unset would make
			// the handler see no code at all, refuse every request, and put
			// the credential in a URL for anyone who then sent it the "right"
			// way.
			"code":          withSource(totpOptionalCodeParam("Current authenticator code. Send this OR recovery_code."), apischema.SourceBody),
			"recovery_code": withSource(totpRecoveryCodeParam, apischema.SourceBody),
		},
		Handler: h.Disable,
	})
	reg.Register(Endpoint{
		Method:      fiber.MethodGet,
		Path:        totpScope + "/status",
		Description: "Report whether the caller has a second factor enrolled, and how many recovery codes are left.",
		Group:       "Two-Factor Authentication",
		Permissions: Permissions{SelfService: "reports the caller's own enrollment"},
		Parameters:  apischema.Properties{},
		Handler:     h.Status,
	})
	reg.Register(Endpoint{
		Method: fiber.MethodPost,
		Path:   totpScope + "/recovery-codes/regenerate",
		Description: "Replace the caller's own recovery codes, which invalidates every previous one. " +
			"Requires a current authenticator code — a recovery code is deliberately not accepted here.",
		Group:       "Two-Factor Authentication",
		Permissions: Permissions{SelfService: "regenerates the caller's own recovery codes"},
		Parameters: apischema.Properties{
			"code": totpRequiredCodeParam("Current code from the authenticator."),
		},
		Handler: h.RegenerateRecoveryCodes,
	})

	// The one route in this domain that acts on somebody else. It hangs off
	// /users/:id rather than /auth/totp because the subject is a USER, which is
	// also why it is the only one that needs a grant.
	reg.Register(Endpoint{
		Method: fiber.MethodDelete,
		Path:   userScope + "/:id/totp",
		Description: "Clear another user's 2FA enrollment, for the operator who has to get a locked-out " +
			"colleague back in. A caller cannot reset their OWN this way — that is the self-service " +
			"disable, which requires a code.",
		Group:       "Two-Factor Authentication",
		Permissions: globalCheck("manage", "user"),
		Parameters:  apischema.Properties{"id": userIDParam},
		Handler:     h.AdminReset,
	})
}

// withSource returns p read from src.
//
// It exists so that a shared parameter definition can be reused on a route
// whose verb resolves an unsourced parameter somewhere else — DELETE reads from
// the query string, and the two credentials on the TOTP disable arrive in a
// JSON body. Property is a value type, so this is a copy rather than a mutation
// of the shared definition.
func withSource(p apischema.Property, src apischema.Source) apischema.Property {
	p.Source = src
	return p
}
