package notifications

import (
	"context"
	"encoding/json"
	"fmt"
	"html"
	"strings"
)

type smtpConfig struct {
	Host            string   `json:"host"`
	Port            int      `json:"port"`
	Username        string   `json:"username"`
	Password        string   `json:"password"`
	From            string   `json:"from"`
	To              []string `json:"to"`
	TLS             *bool    `json:"tls,omitempty"`
	SubjectTemplate string   `json:"subject_template"`
}

// useSTARTTLS reports whether the dispatcher should perform a STARTTLS
// upgrade. Defaults to true (mandatory) when the field is absent.
func (c smtpConfig) useSTARTTLS() bool {
	if c.TLS == nil {
		return true
	}
	return *c.TLS
}

// SMTPDispatcher sends alert notifications via email.
type SMTPDispatcher struct{}

func (d *SMTPDispatcher) Type() string { return "email" }

func (d *SMTPDispatcher) Send(ctx context.Context, config json.RawMessage, payload AlertPayload) error {
	var cfg smtpConfig
	if err := json.Unmarshal(config, &cfg); err != nil {
		return fmt.Errorf("parse email config: %w", err)
	}
	if cfg.Host == "" || len(cfg.To) == 0 {
		return fmt.Errorf("email config: host and at least one recipient required")
	}
	if cfg.Port == 0 {
		cfg.Port = 587
	}

	subject := fmt.Sprintf("[%s] %s on %s", strings.ToUpper(payload.Severity), payload.RuleName, payload.ResourceName)
	if cfg.SubjectTemplate != "" {
		if rendered, err := renderTemplate(cfg.SubjectTemplate, payload); err == nil {
			subject = rendered
		}
	}

	body := buildEmailBody(payload)

	// Sanitize headers to prevent CRLF injection.
	safeFrom := sanitizeHeader(cfg.From)
	safeTo := sanitizeHeader(strings.Join(cfg.To, ", "))
	safeSubject := sanitizeHeader(subject)

	msg := fmt.Sprintf("From: %s\r\nTo: %s\r\nSubject: %s\r\nMIME-Version: 1.0\r\nContent-Type: text/html; charset=\"UTF-8\"\r\n\r\n%s",
		safeFrom, safeTo, safeSubject, body)

	return SendSMTPMessage(ctx, SMTPSendOptions{
		Host:        cfg.Host,
		Port:        cfg.Port,
		Username:    cfg.Username,
		Password:    cfg.Password,
		From:        cfg.From,
		To:          cfg.To,
		Message:     []byte(msg),
		UseSTARTTLS: cfg.useSTARTTLS(),
	})
}

func buildEmailBody(p AlertPayload) string {
	color := "#3B82F6"
	switch p.Severity {
	case "critical":
		color = "#DC2626"
	case "warning":
		color = "#F59E0B"
	}

	return fmt.Sprintf(`<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;background:#f4f4f5;padding:20px">
<div style="max-width:600px;margin:0 auto;background:white;border-radius:8px;overflow:hidden">
  <div style="background:%s;color:white;padding:16px 24px">
    <h2 style="margin:0">%s Alert: %s</h2>
  </div>
  <div style="padding:24px">
    <table style="width:100%%;border-collapse:collapse">
      <tr><td style="padding:8px 0;font-weight:bold;width:140px">Resource</td><td>%s</td></tr>
      <tr><td style="padding:8px 0;font-weight:bold">Metric</td><td>%s</td></tr>
      <tr><td style="padding:8px 0;font-weight:bold">Condition</td><td>%s %s %.2f</td></tr>
      <tr><td style="padding:8px 0;font-weight:bold">Current Value</td><td>%.2f</td></tr>
      <tr><td style="padding:8px 0;font-weight:bold">State</td><td>%s</td></tr>
      <tr><td style="padding:8px 0;font-weight:bold">Fired At</td><td>%s</td></tr>
    </table>
    %s
  </div>
  <div style="padding:16px 24px;border-top:1px solid #e4e4e7;color:#71717a;font-size:12px">
    This alert was generated by Nexara.
  </div>
</div>
</body>
</html>`,
		color,
		html.EscapeString(strings.ToUpper(p.Severity)), html.EscapeString(p.RuleName),
		html.EscapeString(p.ResourceName),
		html.EscapeString(p.Metric),
		html.EscapeString(p.Metric), html.EscapeString(p.Operator), p.Threshold,
		p.CurrentValue,
		html.EscapeString(p.State),
		html.EscapeString(p.FiredAt),
		func() string {
			if p.Message != "" {
				return fmt.Sprintf(`<div style="margin-top:16px;padding:12px;background:#f4f4f5;border-radius:4px">%s</div>`, html.EscapeString(p.Message))
			}
			return ""
		}(),
	)
}
